"""empty message

Revision ID: ab317f48e7e7
Revises: 8a9358044145
Create Date: 2022-01-25 21:31:36.153450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab317f48e7e7'
down_revision = '8a9358044145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_done')
    # ### end Alembic commands ###
